INSERT INTO Authors (name) VALUES ('Justinas Marcinkevičius'), ('Jonas Biliūnas'), ('Kazys Binkis');
INSERT INTO Books (authorId, title, year) VALUES (8, 'Grybų karas', 1995), (9, 'Liūdna pasaka', 1906), (10, 'Atžalynas', 1937);
UPDATE Books SET authorId=4 WHERE bookId=2;
DELETE FROM Authors WHERE authorId BETWEEN 8 AND 10;
DELETE FROM Books USING Books LEFT JOIN Authors ON Books.authorId=Authors.authorId WHERE name IS NULL;
CREATE TABLE Genres (genreId INT PRIMARY KEY AUTO_INCREMENT, genre VARCHAR(255));
ALTER TABLE Books ADD genreId INT;
CREATE TABLE BooksAuthors (bookId INT, authorId INT);
INSERT INTO BooksAuthors (bookId, authorId) SELECT bookId, authorId FROM Books;
ALTER TABLE Books DROP COLUMN authorId;
INSERT INTO Genres (genre) VALUE ('Drama');
INSERT INTO Genres (genre) VALUE ('Graphic novel');
INSERT INTO Genres (genre) VALUE ('Poem');
INSERT INTO Genres (genre) VALUE ('Myth');
INSERT INTO Genres (genre) VALUE ('Novel');
INSERT INTO Genres (genre) VALUE ('Short story');
UPDATE Books SET genreId=1 WHERE (bookId) IN (2,3,4);
ALTER DATABASE akademija CHARACTER SET utf8 COLLATE utf8_lithuanian_ci;
INSERT INTO Books (title, year) VALUES ('Laukinė kriaušė', 2013);
